name: Schedule-Update

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - run: dotnet run -c Release PlatformStatusTracker -p PlatformStatusTracker/PlatformStatusTracker.Updater/PlatformStatusTracker.Updater.csproj
